version: "3.7"

services:
  frontend:
    build:
        context: .
        target: production
        # for production, these should be available as args as webpack can not access these variable after prod build
        args:
            - SOCKET_URL=$SOCKET_URL
    image: docker.prakashk.com/network/frontend:master
    env_file: .env
