version: "3.4"

services:
  dev:
    build:
      context: .
      target: builder
    image: frontend_dev
    container_name: frontend_dev
    volumes:
      - .:/usr/app
    ports:
      - 3000:3000
      - 3001:3001
    # this will copy node_modules to src folder, otherwise node_modules will be wipeed out as we don't
    # have the node_modules in the host machine
    command: /usr/app/entrypoint.sh dev
    environment:
      - NODE_ENV=development

  prod:
    build: .
    image: frontend_prod
    container_name: frontend_prod
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
