version: "3.4"

services:
  development:
    build: .
    image: frontend_development
    container_name: frontend_development
    volumes:
      - .:/usr/app
      - /usr/app/node_modules # do not override container node_modules by host node_modules
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

  production:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: frontend_production
    container_name: frontend_production
    ports:
      - 4000:80
    environment:
      - NODE_ENV=production
