version: "3.4"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: docker.bhet-ghat.com/bhetghat/backend:master
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_HOST=mongodb://mongo/bhetghat
      - MONGO_PORT=27017
      - FORCE_COLOR=1
    links:
      - mongo:mongo

  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile.prod
    image: docker.bhet-ghat.com/bhetghat/frontend:master
    environment:
        - NODE_ENV=production
    links:
        - mongo:mongo

  mongo:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
