version: "3.4"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    image: docker.prakashk.com/bhetghat/backend:master
    environment:
      - NODE_ENV=production

  frontend:
    build:
        context: ./frontend
        dockerfile: Dockerfile.prod
    image: docker.prakashk.com/bhetghat/frontend:master
    environment:
        - NODE_ENV=production

