version: "3.4"

services:
  production:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: backend_production
    container_name: backend_production
    ports:
      - 4001:5000
    environment:
      - PORT=5000
      - NODE_ENV=production

  development:
    build: .
    image: backend_development
    container_name: backend_development
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3001:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
