version: "3.4"

services:
  production:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: backend_production
    container_name: backend_production
    ports:
      - 4001:5000
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_HOST=mongodb://mongo/bhetghat
      - MONGO_PORT=27017
      - FORCE_COLOR=1
    links:
      - mongo:mongo

  development:
    build: .
    image: backend_development
    container_name: backend_development
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "3001:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_HOST=mongodb://mongo:27017/bhetghat
      - MONGO_PORT=27017
      - FORCE_COLOR=1
    links:
      - mongo:mongo

  mongo:
    image: "mongo:4.2"
    ports:
      - "27017:27017"
